### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by bayuzauhari** [burdiuz/react-native-codeditor#2]

**Comment by burdiuz** [comment]
@bayuzauhari Hi! I just updated the package to make it "installable". Steps are
1. yarn add react-native-webview
2. react-native link react-native-webview
3. yarn add github:burdiuz/react-native-codeditor

After this you should be able to use it in your react native application

**Comment by burdiuz** [comment]
You may want to subscribe to onInitialized callback, it passes api object as first argument which helps to communicate with code editor. For list of all commands look into 
https://github.com/burdiuz/react-native-codeditor/blob/master/source/event/EditorRequests.js
For more information on each api method check CodeMirror manual, in most cases it's 1:1 replica, just passing arguments.
